# Generated by Django 3.1.3 on 2021-02-17 09:16

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to=posts.models.upload_location)),
                ('date_published', models.DateField(auto_now=True, verbose_name='date published')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='date_updated')),
            ],
        ),
    ]
