# Generated by Django 3.1.3 on 2021-02-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
