# Generated by Django 3.1.3 on 2021-02-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
